spring:
  application:
    name:clothes-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mail:
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_PASSWORD:}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: utf-8




cloudinary:
  name: ${CLOUD_NAME:}
  api-key: ${API_KEY:}
  api-secret: ${API_SECRET:}


secret_key: ${SECRET_KEY:}

token_shop: ${TOKEN_SHOP_GHN:}
shop_id: ${SHOP_ID:}





